export const ESSAY_LIST_REQUEST = "ESSAY_LIST_REQUEST";
export const ESSAY_LIST_SUCCESS = "ESSAY_LIST_SUCCESS";
export const ESSAY_LIST_FAIL = "ESSAY_LIST_FAIL";

export const ESSAY_CREATE_REQUEST = "ESSAY_CREATE_REQUEST";
export const ESSAY_CREATE_SUCCESS = "ESSAY_CREATE_SUCCESS";
export const ESSAY_CREATE_FAIL = "ESSAY_CREATE_FAIL";

export const ESSAY_UPDATE_REQUEST = "ESSAY_UPDATE_REQUEST";
export const ESSAY_UPDATE_SUCCESS = "ESSAY_UPDATE_SUCCESS";
export const ESSAY_UPDATE_FAIL = "ESSAY_UPDATE_FAIL";

export const ESSAY_DELETE_REQUEST = "ESSAY_DELETE_REQUEST";
export const ESSAY_DELETE_SUCCESS = "ESSAY_DELETE_SUCCESS";
export const ESSAY_DELETE_FAIL = "ESSAY_DELETE_FAIL";
