export const QUESTIONS_LIST_REQUEST = "QUESTIONS_LIST_REQUEST";
export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS";
export const QUESTIONS_LIST_FAIL = "QUESTIONS_LIST_FAIL";

export const QUESTIONS_CREATE_REQUEST = "QUESTIONS_CREATE_REQUEST";
export const QUESTIONS_CREATE_SUCCESS = "QUESTIONS_CREATE_SUCCESS";
export const QUESTIONS_CREATE_FAIL = "QUESTIONS_CREATE_FAIL";

export const QUESTIONS_UPDATE_REQUEST = "QUESTIONS_UPDATE_REQUEST";
export const QUESTIONS_UPDATE_SUCCESS = "QUESTIONS_UPDATE_SUCCESS";
export const QUESTIONS_UPDATE_FAIL = "QUESTIONS_UPDATE_FAIL";

export const QUESTIONS_DELETE_REQUEST = "QUESTIONS_DELETE_REQUEST";
export const QUESTIONS_DELETE_SUCCESS = "QUESTIONS_DELETE_SUCCESS";
export const QUESTIONS_DELETE_FAIL = "QUESTIONS_DELETE_FAIL";
