export const TODOS_LIST_REQUEST = "TODOS_LIST_REQUEST";
export const TODOS_LIST_SUCCESS = "TODOS_LIST_SUCCESS";
export const TODOS_LIST_FAIL = "TODOS_LIST_FAIL";

export const TODOS_CREATE_REQUEST = "TODOS_CREATE_REQUEST";
export const TODOS_CREATE_SUCCESS = "TODOS_CREATE_SUCCESS";
export const TODOS_CREATE_FAIL = "TODOS_CREATE_FAIL";

export const TODOS_UPDATE_REQUEST = "TODOS_UPDATE_REQUEST";
export const TODOS_UPDATE_SUCCESS = "TODOS_UPDATE_SUCCESS";
export const TODOS_UPDATE_FAIL = "TODOS_UPDATE_FAIL";

export const TODOS_DELETE_REQUEST = "TODOS_DELETE_REQUEST";
export const TODOS_DELETE_SUCCESS = "TODOS_DELETE_SUCCESS";
export const TODOS_DELETE_FAIL = "TODOS_DELETE_FAIL";
